- name: Load vars from secrets.yml
  include_vars:
    file: secrets.yml

- name: Common playbook
  hosts: all
  roles:
    - role: common
      tags: common

- name: Proxmox Qemu playbook
  hosts: proxmox_proxmox_qemu
  roles:
    - role: proxmox_qemu
      tags: proxmox_qemu

- name: DNS Slave playbook
  hosts: slaves
  roles:
    - role: dns_slave
      tags: dns_slave

- name: Prometheus playbook
  hosts: group_prometheus
  roles:
    - role: prometheus
      tags: prometheus

- name: Proxmox playbook
  hosts: proxmox_nodes
  roles:
    - role: proxmox
      tags: proxmox
