# - name: Create pvebackup service
#   template:
#     src: pvebackup.service.j2
#     dest: /etc/systemd/system/pvebackup.service
#     owner: root
#     group: root
#     mode: 0644

 #- name: Create pvebackup timer
 #  copy:
 #    src: pvebackup.timer
 #    dest: /etc/systemd/system/pvebackup.timer
 #    owner: root
 #    group: root
 #    mode: 0644

 #- name: Ensure timer started and enabled
 #  systemd:
 #    name: pvebackup.timer
 #    state: started
 #    enabled: yes

 - name: Install borgbackup, borgmatic, numad, and sysfsutils
   apt:
     name: "{{ item }}"
     state: present
   with_items:
     - borgbackup
     - borgmatic
     - numad
     - sysfsutils

 - name: Create /etc/borgmatic
   file:
     path: /etc/borgmatic
     state: directory
     owner: root
     group: root
     mode: 0755

 - name: Copy /etc/borgmatic/config.yaml
   template:
     src: borgmatic_config.yaml.j2
     dest: /etc/borgmatic/config.yaml
     owner: root
     group: root
     mode: 0640

 - name: numad started and enabled
   systemd:
     name: numad
     state: started
     enabled: yes

 - name: set /sys/kernel/mm/ksm/merge_across_nodes to 0 (persistent using sysfs.d)
   copy:
     content: |
       kernel/mm/ksm/merge_across_nodes = 0
     dest: /etc/sysfs.d/ksm.conf
     owner: root
     group: root
     mode: 0644
    
# libpam-google-authenticator
# lmsensors
# ksmtuned ksm-control-daemon
# linux-cpupower
# freeipmi
# pve-headers
# unattended-upgrades
# cockpit
# prometheus-node-exporter-collectors
# lshw