#!/bin/bash

host=$(hostname)

/sbin/aureport -k -ts yesterday 00:00:00 -te yesterday 23:59:59 | /bin/grep -q "^<no events of interest were found>" || /sbin/aureport -k -ts yesterday 00:00:00 -te yesterday 23:59:59 | mailx -s "audit report on ${host}" root

# rotates logs
pkill -USR1 -x auditd
