export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

alias ..="cd .."

export EDITOR=micro

PS1='%F{cyan}%n%f@%F{green}%m:%F{yellow}%~%f$ '