- name: restart netdata
  systemd:
    name: netdata
    state: restarted
    enabled: yes
    daemon_reload: yes
- name: restart systemd-journald
  systemd:
    name: systemd-journald
    state: restarted
    enabled: yes
    daemon_reload: yes
- name: reload superb rules
  command: sysctl -p /etc/sysctl.d/99-superb.conf