- name: restart netdata
  systemd:
    name: netdata
    state: restarted
    enabled: yes
    daemon_reload: yes
- name: restart systemd-journald
  systemd:
    name: systemd-journald
    state: restarted
    enabled: yes
    daemon_reload: yes
- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
    enabled: yes
    daemon_reload: yes
- name: reload superb rules
  command: sysctl -p /etc/sysctl.d/99-superb.conf
- name: restart glances
  systemd:
    name: glances
    state: restarted
    enabled: yes
    daemon_reload: yes
- name: reload sshd
  systemd:
    name: ssh
    state: reloaded
    enabled: yes
    daemon_reload: yes
- name: update grub
  command: update-grub
- name: restart auditd
  systemd:
    name: auditd
    state: restarted
    enabled: yes
    daemon_reload: yes
