server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      path: /var/log/journal/remote      
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: "unit"
      - source_labels: ["__journal__hostname"]
        target_label: "hostname"
      - source_labels: ["__journal__boot_id"]
        target_label: "boot_id"
      - source_labels: ["__journal__machine_id"]
        target_label: "machine_id"
      - source_labels: ["__journal__transport"]
        target_label: "transport"
      - source_labels: ["__journal__cursor"]
        target_label: "cursor"
      - source_labels: ["__journal__syslog_identifier"]
        target_label: "syslog_identifier"
      - source_labels: ["__journal__syslog_facility"]
        target_label: "syslog_facility"
      - source_labels: ["__journal__syslog_priority"]
        target_label: "syslog_priority"
      - source_labels: ["__journal__syslog_pid"]
        target_label: "syslog_pid"
      - source_labels: ["__journal__syslog_tid"]
        target_label: "syslog_tid"