- name: Enable remote journal socket
  systemd:
    name: systemd-journal-remote.socket
    enabled: yes

- name: Override systemd-journal-remote.service
  copy:
    dest: /etc/systemd/system/systemd-journal-remote.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=/lib/systemd/systemd-journal-remote --listen-http=-3 --output=/var/log/journal/remote/
    owner: root
    group: root
    mode: 0644

- name: Enable remote journal sink service
  systemd:
    name: systemd-journal-remote.service
    enabled: yes
    state: started
  
- name: Install loki
  apt:
    name: loki
    state: present
- name: Enable loki
  systemd:
    name: loki
    enabled: yes
    state: started
- name: Install promtail
  apt:
    name: promtail
    state: present
- name: Enable promtail
  systemd:
    name: promtail
    enabled: yes
    state: started

- name: Configure promtail to read /var/log/journal/remote and forward it to loki
  copy:
    dest: /etc/promtail/config.yml
    src: promtail-config.yml
  notify: restart promtail

- name: /var/lib/loki
  file:
    path: /var/lib/loki
    state: directory
    owner: loki
    group: root
    mode: 0755

- name: Configure loki (copy)
  copy:
    src: loki-config.yml
    dest: /etc/loki/config.yml
    owner: loki
    group: root
    mode: 0644
  notify: restart loki

- name: Add promtail to systemd-journal group
  user:
    name: promtail
    groups: systemd-journal
    append: yes

- name: Add promtail to systemd-journal-remote group
  user:
    name: promtail
    groups: systemd-journal-remote
    append: yes