- name: restart coredns
  systemd:
    name: coredns
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
    enabled: yes    