- name: install auditd
  apt:
    name: auditd
    state: present
  when: inventory_hostname != "demon"

- name: copy file /etc/audit/rules.d/audit.rules
  copy:
    src: audit.rules
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname != "demon"
  notify: restart auditd

- name: copy file aureport (cron)
  copy:
    src: aureport
    dst: /etc/cron.daily/aureport
    owner: root
    group: root
    mode: 0744
  when: inventory_hostname != "demon"
