- name: search domain
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^Domains='
    line: 'Domains=hetmer.net'
    state: present

- name: resolve on cf
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNS='
    line: 'DNS=2606:4700:4700::1111#cloudflare-dns.com 2606:4700:4700::1001#cloudflare-dns.com 1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com'
    state: present
  notify: restart systemd-resolved

- name: dot on
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSOverTLS='
    line: 'DNSOverTLS=yes'
    state: present
  when: ansible_host != "mail"

- name: dnssec on
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSSEC='
    line: 'DNSSEC=yes'
    state: present

- name: resolve fallback on quad9 (v4 first)
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^FallbackDNS='
    line: 'FallbackDNS=9.9.9.11#dns11.quad9.net 149.112.112.11#dns11.quad9.net 2620:fe::11#dns11.quad9.net 2620:fe:fe::11#dns11.quad9.net'
    state: present
  notify: restart systemd-resolved
