- name: copy file /etc/systemd/resolved.conf
  copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_host != "mail"

# ensure DNSStubListener=no is disabled
- name: disable DNSStubListener mail
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSStubListener='
    line: 'DNSStubListener=no'
    state: present
    backup: yes
  when: ansible_host == "mail"

    
