- name: search domain
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^Domains='
    line: 'Domains=hetmer.net'
    state: present

- name: resolve on google
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNS='
    line: 'DNS=2001:4860:4860::8888#dns.google 2001:4860:4860::8844#dns.google 8.8.8.8#dns.google 8.8.4.4#dns.google'
    state: present
  when: ansible_host != "mail"

- name: resolve fallback on cf
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^FallbackDNS='
    line: 'FallbackDNS=1.1.1.1#cloudflare-dns.com 1.0.0.1#cloudflare-dns.com 2606:4700:4700::1111#cloudflare-dns.com 2606:4700:4700::1001#cloudflare-dns.com'
    state: present

- name: disable DNSStubListener on mail
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSStubListener='
    line: 'DNSStubListener=no'
    state: present
  when: ansible_host == "mail"

- name: resolve mail on local (dnsbl hack)
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNS='
    line: 'DNS=::1'
    state: present
  when: ansible_host == "mail"
