- name: Set fish as default shell for root user
  user:
    name: root
    shell: /usr/bin/fish

- name: Set fish as default shell for toto
  user:
    name: "{{ item }}"
    shell: /usr/bin/fish
  with_items:
    - toto
    
- name: add toto to adm group
  user:
    name: toto
    groups: adm
    append: yes

#- name: copy file /root/.zshrc
#  copy:
#    src: zshrc
#    dest: /root/.zshrc
#    owner: root
#    group: root
#    mode: 0644

#- name: copy file /home/toto/.zshrc
#  copy:
#    src: zshrc
#    dest: /home/toto/.zshrc
#    owner: toto
#    group: toto
#    mode: 0644
