- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: reload sshd
- name: Ensure password auth disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: reload sshd

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: toto
    state: present
    key: "{{ lookup('file', '/Users/toto/.ssh/id_ed25519.pub') }}"