- name: set journald storage to volatile
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: '^#?Storage='
    line: 'Storage=volatile'
    state: present
  notify: restart systemd-journald
  
- name: disable and stop rsyslogd
  systemd:
    name: rsyslog
    state: stopped
    enabled: no

- name: purge rsyslog when installed
  package:
    name: rsyslog
    state: absent
  when: ansible_facts.packages['rsyslog'] is defined
    
- name: edit journal-upload.conf
  lineinfile:
    dest: /etc/systemd/journal-upload.conf
    regexp: '^#?URL='
    line: 'URL=http://172.16.0.217:19532'

- name: systemd override systemd-journal-upload to keep restarting
  copy:
    content: |
      [Service]
      Restart=always
    dest: /etc/systemd/system/systemd-journal-upload.service.d/override.conf
    owner: root
    group: root
    mode: 0644

- name: enable and start systemd-journal-upload
  systemd:
    name: systemd-journal-upload
    state: started
    enabled: yes