- name: Install /etc/udev/rules.d/60-scheduler.rules
  copy:
    content: |
      # Set mq-deadline on all disks, persistent using udev, for all disks sd[a-z]
      ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/scheduler}="mq-deadline"
      # Set mq-deadline on all disks, persistent using udev, for all disks vd[a-z]
      ACTION=="add|change", KERNEL=="vd[a-z]", ATTR{queue/scheduler}="none"
    dest: /etc/udev/rules.d/60-scheduler.rules
    owner: root
    group: root
    mode: 0644

- name: Copy /usr/share/systemd/tmp.mount to /etc/systemd/system/tmp.mount, remote_src
  copy:
    src: /usr/share/systemd/tmp.mount
    dest: /etc/systemd/system/tmp.mount
    remote_src: yes
    owner: root
    group: root
    mode: 0644

- name: enable and start tmp.mount
  systemd:
    name: tmp.mount
    state: started
    enabled: yes

- name: Replace defaults in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(?!#)(\S+\s+\S+\s+\S+\s+)defaults(\s+.*)$'
    replace: '\1defaults,noatime,nodiratime\2'

- name: Replace discard,errors=remount-ro in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(?!#)(\S+\s+\S+\s+\S+\s+)discard,errors=remount-ro(\s+.*)$'
    replace: '\1defaults,noatime,nodiratime\2'

- name: Install superb sysctl rules! to 99-superb.conf
  copy:
    src: 99-superb.conf
    dest: /etc/sysctl.d/99-superb.conf
    owner: root
    group: root
    mode: 0644
  notify: reload superb rules