- name: Apt electrolux
  apt:
    autoremove: yes
    purge: yes

- name: Install /etc/udev/rules.d/60-scheduler.rules
  copy:
    content: |
      ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/scheduler}="mq-deadline"
      ACTION=="add|change", KERNEL=="vd[a-z]", ATTR{queue/scheduler}="none"
    dest: /etc/udev/rules.d/60-scheduler.rules
    owner: root
    group: root
    mode: 0644
  when: not ansible_virtualization_type == "lxc"

- name: Copy /usr/share/systemd/tmp.mount to /etc/systemd/system/tmp.mount, remote_src
  copy:
    src: /usr/share/systemd/tmp.mount
    dest: /etc/systemd/system/tmp.mount
    remote_src: yes
    owner: root
    group: root
    mode: 0644

- name: enable and start tmp.mount
  systemd:
    name: tmp.mount
    state: started
    enabled: yes

- name: Set da magic for ext4 discard
  replace:
     path: /etc/fstab
     regexp: '^(?!#)(\S+)\s+(\S+)\s+(ext4)\s+(discard[a-z,]+)\s+(\S)\s(\S)\S*$'
     replace: '\1 \2 \3 defaults,noatime,nodiratime,lazytime,commit=60 \5 \6'

- name: Set da magic for ext4
  replace:
     path: /etc/fstab
     regexp: '^(?!#)(\S+)\s+(\S+)\s+(ext4)\s+(defaults[a-z,]+)\s+(\S)\s(\S)\S*$'
     replace: '\1 \2 \3 defaults,noatime,nodiratime,lazytime,commit=60 \5 \6'

- name: Set da magic for xfs and who killed captain alex
  replace:
     path: /etc/fstab
     regexp: '^(?!#)(\S+)\s+(\S+)\s+(xfs)\s+(defaults[a-z,]+)\s+(\S)\s(\S)\S*$'
     replace: '\1 \2 \3 defaults,noatime,nodiratime,lazytime \5 \6'

- name: Install superb sysctl rules! to 99-superb.conf
  template:
    src: 99-superb.conf.j2
    dest: /etc/sysctl.d/99-superb.conf
    owner: root
    group: root
    mode: 0644
  notify: reload superb rules
  ignore_errors: true
  when: not ansible_virtualization_type == "lxc"

- name: Nuke mitigation to hell
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="quiet splash mitigations=off l1tf=off tsx=on tsx_async_abort=off"'
    state: present
  when: not ansible_virtualization_type == "lxc"
  notify: update grub