- name: Set Zsh as default shell for root user
  user:
    name: root
    shell: /usr/bin/zsh

- name: Set Zsh as default shell for toto
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items:
    - toto

- name: copy file /root/.zshrc
  copy:
    src: zshrc
    dest: /root/.zshrc
    owner: root
    group: root
    mode: 0644

- name: copy file /home/toto/.zshrc
  copy:
    src: zshrc
    dest: /home/toto/.zshrc
    owner: toto
    group: toto
    mode: 0644
