- name: reload prometheus
  systemd:
    name: prometheus
    state: reloaded
- name: restart netdata
  systemd:
    name: netdata
    state: restarted
- name: restart loki
  systemd:
    name: loki
    state: restarted
- name: restart promtail
  systemd:
    name: promtail
    state: restarted